openapi: 3.0.2
info:
  title: ECE 461 - Fall 2025 - Project Phase 2 (BASELINE path-level params for /artifact/{artifact_type})
  version: 3.4.2
  description: |
    Path-level parameters as defined in baseline_endpoints.yaml for /artifact/{artifact_type}
paths:
  /artifact/{artifact_type}:
    parameters:
      - name: artifact_type
        description: Type of artifact being ingested.
        schema:
          $ref: "#/components/schemas/ArtifactType"
        in: path
        required: true
      - name: X-Authorization
        description: ""
        schema:
          $ref: "#/components/schemas/AuthenticationToken"
        in: header
        required: true
components:
  schemas:
    AuthenticationToken:
      type: string
    ArtifactType:
      type: string
      enum: [model, dataset, code]
