openapi: 3.0.2
info:
  title: ECE 461 - Fall 2025 - Project Phase 2 (BASELINE path-level params for /artifacts/{artifact_type}/{id})
  version: 3.4.2
  description: |
    Path-level parameters as defined in baseline_endpoints.yaml for /artifacts/{artifact_type}/{id}
paths:
  /artifacts/{artifact_type}/{id}:
    parameters:
      - examples:
          ExampleID:
            value: model
        name: artifact_type
        description: Artifact type
        schema:
          $ref: "#/components/schemas/ArtifactType"
        in: path
        required: true
      - examples:
          ExampleID:
            value: 3847247294
        name: id
        description: artifact id
        schema:
          $ref: "#/components/schemas/ArtifactID"
        in: path
        required: true
      - examples:
          ExampleToken:
            value: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        name: X-Authorization
        description: ""
        schema:
          $ref: "#/components/schemas/AuthenticationToken"
        in: header
        required: true
components:
  schemas:
    AuthenticationToken:
      type: string
    ArtifactType:
      type: string
      enum: [model, dataset, code]
    ArtifactID:
      type: string
