openapi: 3.0.2
info:
  title: ECE 461 - Fall 2025 - Project Phase 2 (BASELINE endpoint: /artifact/{artifact_type} POST)
  version: 3.4.2
  description: |
    Single-endpoint extract for POST /artifact/{artifact_type}
paths:
  /artifact/{artifact_type}:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ArtifactData"
            examples:
              ExampleArtifactData:
                value:
                  url: https://huggingface.co/google-bert/bert-base-uncased
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Artifact"
              examples:
                ExampleArtifactDataResponse:
                  value:
                    metadata:
                      name: bert-base-uncased
                      id: 9078563412
                      type: model
                    data:
                      url: https://huggingface.co/google-bert/bert-base-uncased
          description: |
            Success. Check the id in the returned metadata for the official ID.
        "400":
          description: There is missing field(s) in the artifact_data or it is formed improperly (must include a single url).
        "403":
          description: Authentication failed due to invalid or missing AuthenticationToken.
        "409":
          description: Artifact exists already.
        "424":
          description: Artifact is not registered due to the disqualified rating.
      operationId: ArtifactCreate
      summary: Register a new artifact. (BASELINE)
      description: |
        Register a new artifact by providing a downloadable source url. Artifacts may share a name with existing entries; refer to the description above to see how an id is formed for an artifact.
    parameters:
      - name: artifact_type
        description: Type of artifact being ingested.
        schema:
          $ref: "#/components/schemas/ArtifactType"
        in: path
        required: true
      - name: X-Authorization
        description: ""
        schema:
          $ref: "#/components/schemas/AuthenticationToken"
        in: header
        required: true
components:
  schemas:
    AuthenticationToken:
      description: |
        The spec permits you to use any token format you like. You could, for example, look into JSON Web Tokens ("JWT", pronounced "jots"): https://jwt.io.
      type: string
    Artifact:
      description: Artifact envelope containing metadata and ingest details.
      required: [metadata, data]
      type: object
      properties:
        metadata:
          $ref: "#/components/schemas/ArtifactMetadata"
        data:
          $ref: "#/components/schemas/ArtifactData"
    ArtifactData:
      description: |-
        Source location for ingesting an artifact.

        Provide a single downloadable url pointing to a bundle that contains the artifact assets.
      required: [url]
      type: object
      properties:
        url:
          description: Artifact source url used during ingest.
          type: string
          format: uri
    ArtifactMetadata:
      description: |-
        The `name` is provided when uploading an artifact.

        The `id` is used as an internal identifier for interacting with existing artifacts and distinguishes artifacts that share a name.
      required: [name, id, type]
      type: object
      properties:
        name:
          $ref: "#/components/schemas/ArtifactName"
        id:
          $ref: "#/components/schemas/ArtifactID"
        type:
          $ref: "#/components/schemas/ArtifactType"
    ArtifactType:
      description: "Artifact category."
      type: string
      enum: [model, dataset, code]
    ArtifactID:
      description: "Unique identifier for use with artifact endpoints."
      example: "48472749248"
      type: string
      pattern: '^[a-zA-Z0-9\-]+$'
    ArtifactName:
      description: |
        Name of an artifact.

        - Names should only use typical "keyboard" characters.
        - The name "*" is reserved. See the `/artifacts` API for its meaning.
      type: string
