openapi: 3.0.2
info:
  title: ECE 461 - Fall 2025 - Project Phase 2 (BASELINE endpoint: /artifacts/{artifact_type}/{id} PUT)
  version: 3.4.2
  description: |
    Single-endpoint extract for PUT /artifacts/{artifact_type}/{id}
paths:
  /artifacts/{artifact_type}/{id}:
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Artifact"
        required: true
      parameters:
        - name: artifact_type
          description: Type of artifact to update
          schema:
            $ref: "#/components/schemas/ArtifactType"
          in: path
          required: true
        - name: id
          description: artifact id
          schema:
            $ref: "#/components/schemas/ArtifactID"
          in: path
          required: true
      responses:
        "200":
          description: Artifact is updated.
        "400":
          description: "There is missing field(s) in the artifact_type or artifact_id or it is formed improperly, or is invalid."
        "403":
          description: Authentication failed due to invalid or missing AuthenticationToken.
        "404":
          description: Artifact does not exist.
      operationId: ArtifactUpdate
      summary: Update this content of the artifact. (BASELINE)
      description: |
        The name and id must match.

        The artifact source (from artifact_data) will replace the previous contents.
    parameters:
      - examples:
          ExampleID:
            value: model
        name: artifact_type
        description: Artifact type
        schema:
          $ref: "#/components/schemas/ArtifactType"
        in: path
        required: true
      - examples:
          ExampleID:
            value: 3847247294
        name: id
        description: artifact id
        schema:
          $ref: "#/components/schemas/ArtifactID"
        in: path
        required: true
      - examples:
          ExampleToken:
            value: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        name: X-Authorization
        description: ""
        schema:
          $ref: "#/components/schemas/AuthenticationToken"
        in: header
        required: true
components:
  schemas:
    AuthenticationToken:
      description: |
        The spec permits you to use any token format you like. You could, for example, look into JSON Web Tokens ("JWT", pronounced "jots"): https://jwt.io.
      type: string
    Artifact:
      description: Artifact envelope containing metadata and ingest details.
      required: [metadata, data]
      type: object
      properties:
        metadata:
          $ref: "#/components/schemas/ArtifactMetadata"
        data:
          $ref: "#/components/schemas/ArtifactData"
    ArtifactData:
      description: |-
        Source location for ingesting an artifact.

        Provide a single downloadable url pointing to a bundle that contains the artifact assets.
      required: [url]
      type: object
      properties:
        url:
          description: Artifact source url used during ingest.
          type: string
          format: uri
    ArtifactMetadata:
      description: |-
        The `name` is provided when uploading an artifact.

        The `id` is used as an internal identifier for interacting with existing artifacts and distinguishes artifacts that share a name.
      required: [name, id, type]
      type: object
      properties:
        name:
          $ref: "#/components/schemas/ArtifactName"
        id:
          $ref: "#/components/schemas/ArtifactID"
        type:
          $ref: "#/components/schemas/ArtifactType"
    ArtifactType:
      description: "Artifact category."
      type: string
      enum: [model, dataset, code]
    ArtifactID:
      description: "Unique identifier for use with artifact endpoints."
      example: "48472749248"
      type: string
      pattern: '^[a-zA-Z0-9\-]+$'
    ArtifactName:
      description: |
        Name of an artifact.

        - Names should only use typical "keyboard" characters.
        - The name "*" is reserved. See the `/artifacts` API for its meaning.
      type: string
