openapi: 3.0.2
info:
  title: ECE 461 - Fall 2025 - Project Phase 2 (BASELINE path-level params for /artifact/model/{id})
  version: 3.4.2
  description: |
    Path-level parameters as defined in baseline_endpoints.yaml for /artifact/model/{id}/rate and /artifact/model/{id}/lineage and /artifact/model/{id}/license-check
paths:
  /artifact/model/{id}:
    parameters:
      - name: id
        schema:
          $ref: "#/components/schemas/ArtifactID"
        in: path
        required: true
      - name: X-Authorization
        description: ""
        schema:
          $ref: "#/components/schemas/AuthenticationToken"
        in: header
        required: true
components:
  schemas:
    AuthenticationToken:
      type: string
    ArtifactID:
      type: string
