openapi: 3.0.2
info:
  title: ECE 461 - Fall 2025 - Project Phase 2 (BASELINE endpoint: /health)
  version: 3.4.2
  description: |
    Single-endpoint extract for /health from baseline_endpoints.yaml
paths:
  /health:
    get:
      summary: "Heartbeat check (BASELINE)"
      description: |
        Lightweight liveness probe. Returns HTTP 200 when the registry API is reachable.
      operationId: RegistryHealthHeartbeat
      responses:
        "200":
          description: Service reachable.
components: {}
